# Generated by Django 4.1.5 on 2023-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_catergory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isBought',
            field=models.BooleanField(default=False),
        ),
    ]
