# Generated by Django 4.1.5 on 2023-03-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_course_isbought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='isBought',
        ),
        migrations.AddField(
            model_name='course',
            name='boughtBy',
            field=models.ManyToManyField(blank=True, null=True, related_name='bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='auctions.course')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
