# Generated by Django 4.1.5 on 2023-04-12 07:43

import auctions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_material_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='resource',
            field=models.FileField(upload_to=auctions.utils.get_upload_path),
        ),
    ]
